spring:
  application:
    name: testApp
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/news
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password: secret
      ssl:
        enabled: false


mybatis:
  config-location: classpath:mybatis-config.xml
